### ISSUE TITLE
Volume selection is not accurate enough.

### ISSUE THREAD

**Issue by ric-bianchi** [HSF/Qt3DExaminerViewer#3]
Users should be able to select a volume by left-clicking on the surface of the volume.

However, the volume gets selected even when left-clicking on the "void space" around the volume.

The selection mechanism should be improved. Users should be able to accurately select a single volume in a busy environment.

Could you check and fix this, @huajian1069 ?
Thanks a lot!

Best, -- Riccardo.

**Comment by huajian1069** [comment]
I have checked before. But I still got no luck in this problem. The second issue is caused by the same reason as this one: the default bounding volume picking method cannot be changed by API in documentation. I asked 4 times on the Qt Forum ([see this](https://forum.qt.io/topic/117472/is-this-solved-i-cannot-make-triangle-picking-work)) but has got really helpful answers. I am sad that this problem is still there for long time. 

The only solution I found is that: rewriting the major part of project with QML language. Then a big challenge is how to transfer data between qml and c++ because there are some works such as reading .db file which cannot be handled by qml. I am studying qt3d official examples now. Tell me if I should keep following along this way.

Best,
Huajian

**Comment by huajian1069** [comment]
> Users should be able to select a volume by left-clicking on the surface of the volume.
> 
> However, the volume gets selected even when left-clicking on the "void space" around the volume.
> 
> The selection mechanism should be improved. Users should be able to accurately select a single volume in a busy environment.
> 
> Could you check and fix this, @huajian1069 ?
> Thanks a lot!
> 
> Best, -- Riccardo.

**Comment by ric-bianchi** [comment]
[fixed the link in the comment]

**Comment by ric-bianchi** [comment]
I'm reading the ticket you opened on the Qt forum and the thread you linked there. I'll come back to you after reading that.

**Comment by ric-bianchi** [comment]
Fixed by commit 3201f5b2b0f10aca2c61ecc325a27b706a3278c2
