### ISSUE TITLE
Questions about GSoC.

### ISSUE THREAD

**Issue by bugmaker2** [HSF/Qt3DExaminerViewer#9]
Dear seniors, I am a junior student majoring in communication engineering in UESTC. After getting a preliminary understanding of the materials, I found your project on the project list. I hope to participate in GSoC this year (2021). May I ask what relevant preparations need to be made? Is it difficult for non-computer majors?
学长好，我是一名通信工程专业的大三学生，在初步了解资料后，希望参加今年（2021）的GSoC。
请问需要做什么相关的准备呢？对于非计算机专业学生的是不是较为困难？

**Comment by huajian1069** [comment]
> Dear seniors, I am a junior student majoring in communication engineering in UESTC. After getting a preliminary understanding of the materials, I found your project on the project list. I hope to participate in GSoC this year (2021). May I ask what relevant preparations need to be made? Is it difficult for non-computer majors?
> 学长好，我是一名通信工程专业的大三学生，在初步了解资料后，希望参加今年（2021）的GSoC。
> 请问需要做什么相关的准备呢？对于非计算机专业学生的是不是较为困难？

Hi Baiyuan, to help others with similar questions, I answer in English below.
Don't be afraid because of any problems related to your background, CV(Resume), etc. The most important property is your strong motivation. It's a good sign that you ask questions and pay attention so early. Please also show your motivations for your preferred project **before and during** the application period(March 29, 2021 - April 13, 2021
). You can make your motivations explicit for your mentors by earlier/frequent contacts, well-prepared proposals(All proposals will be submitted by April 13, 2021 20:00 (CEST).) When others review your proposal, be sure to make the following things obvious for others:
- You have put your time into it; You have treated your application seriously;
- You are willing and able to learn quickly;
- You are reliable to deliver what you promise, which is better to not ambiguous or ambitious.

Trust me. Your major in communication engineering is not any disadvantage. To apply for big and hot communities(like TensorFlow, Kubernetes), you have better to learn their domain-specific programming knowledge now. To apply for less-attractive communities, I advise you to review their project ideas list from March at least. I list a few possible soft requirements:
- You need to know their preferred programming language(C++, Python, Scala...). So you don't need to learn from most basic things.
- You have better to know their most-used libraries.

Why I say soft requirements is because if you don't know but you can learn them quickly, it is still no problem. I knew C++ programming, but I didn't know Qt when I applied for this GSOC 2020 project. No one expects you to be an expert already. You are just a student so it is totally fine if you don't know something. Only a few sexy communities are very selective. Decide and do it.

**Comment by bugmaker2** [comment]
Thanks for your detailed advice. And it's also very nice of you to consider using English, this may help a lot to novices like me.
Motivated and well-guided, I am going to make preparations for GSoC.
Best wishes.
